main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    path('explore/', views.Explore.as_view(), name='explore'),
    path('login/', views.Login.as_view(), name='login-page'),
    path('accounts/signup/', views.signup, name='signup'),
    path('mushrooms/', views.mushroom_index, name='mushroom-index'),
    path('mushrooms/<int:mushroom_id>/', views.mushroom_detail, name='mushroom-detail'),
    path('mushrooms/create', views.CreateMushroom.as_view(), name='mushroom-create'),
    path('mushrooms/<int:pk>/update/', views.MushroomUpdate.as_view(), name='mushroom-update'),
    path('mushrooms/<int:pk>/delete/', views.MushroomDelete.as_view(), name='mushroom-delete'),
    path('mushrooms/<int:mushroom_id>/add-tracking/', views.record_mushroom, name='add-tracking'),
]

mushroomcove/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Mushroom(models.Model): 
  name = models.CharField(max_length=100)
  scientific = models.CharField(max_length=100)
  description = models.TextField(max_length=500)

  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
      return reverse("mushroom-detail", kwargs={"mushroom_id": self.pk})

class Tracking(models.Model):
  title = models.CharField(max_length=50)
  date = models.DateField('Tracking Date')
  notes = models.CharField(max_length=500)
  location = models.CharField(max_length=100)

  mushroom = models.ForeignKey(Mushroom, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django import forms
from .models import Tracking

class TrackingFrom(forms.ModelForm):
  class Meta:
    model = Tracking
    fields = ['title', 'date', 'notes', 'location']
    widgets = {
      'date': forms.DateInput(
        format=('%Y-%m-%d'),
        attrs={
          'placeholder': 'Select a date',
          'type': 'date'
        }
      )
    }

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TrackingFrom
from .models import Mushroom

from django.http import HttpResponse

# Classes
class Home(LoginView):
  template_name = 'home.html'

class About(TemplateView):
  template_name = 'about.html'

class Explore(TemplateView):
  template_name = 'explore.html'

class Login(LoginView):
  template_name = 'login.html'

class CreateMushroom(LoginRequiredMixin, CreateView):
  model = Mushroom
  fields = '__all__'

class MushroomUpdate(LoginRequiredMixin, UpdateView):
  model = Mushroom
  fields = '__all__'

class MushroomDelete(LoginRequiredMixin, DeleteView):
  model = Mushroom
  success_url = '/mushrooms/'

# Functions
def mushroom_index(request):
  mushrooms = Mushroom.objects.filter(user=request.user)
  return render(request, 'mushrooms/index.html', {'mushrooms': mushrooms})

def mushroom_detail(request, mushroom_id):
  mushroom = Mushroom.objects.get(id=mushroom_id)
  traking_form = TrackingFrom()
  return render(request, 'mushrooms/detail.html', {
    'mushroom': mushroom,
    'tracking_form': traking_form
  })
  # return render(request, 'mushrooms/detail.html')

def record_mushroom(request, mushroom_id):
  form = TrackingFrom(request.POST)
  if form.is_valid():
    new_tracking = form.save(commit=False)
    new_tracking.mushroom_id = mushroom_id
    new_tracking.save()
  return redirect('mushroom-detail', mushroom_id=mushroom_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid Sign Up - Try Again'
  form = UserCreationForm()
  context = {
    'form': form,
    'error_message': error_message
  }
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static "css/about.css" %}">
{% endblock head %}
{% block content %}
  <section class="image-container">
    <img src="{% static "images/mushroom-forage.jpg" %}" alt="mushroom-forage">
  </section>
  <section class="intro-container">
    <div>
      <h2>Our Mission</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, aspernatur et excepturi tenetur magnam ea ipsum rerum animi fugit at quis, id sed autem accusantium nulla sunt, odit dolor labore.</p>
    </div>
  </section>
  <section class="info-container">
    <div class="info-content-started">
      <h2>What we bring to the table</h2>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas sequi, quibusdam iure, hic dolorum illo earum a nemo aperiam aliquam facilis vero possimus qui, deserunt tempora vitae placeat voluptas. Ipsam.</p>
    </div>
    <div class="info-content-find">
      <img src="{% static "images/mushroom-basket.jpg" %}" alt="mushroom-basket">
      <img src="{% static "images/mushroom2.jpg" %}" alt="mushroom2">
    </div>
  </section>
  <section class="mailing-container">
    <div class="mailing-content blue-gradient">
      <div>
        <h1>JOIN US ON OUR MAILING LIST</h1>
        <p class="mailing-message">Let us send you the latest news and events</p>
      </div>
      <div class="news-letter-signup">
        <label for="email">Email</label>
        <input id="email" type="text">
        <label for="zip">Zip</label>
        <input id="zip" type="text">
        <p>This site is protected by reCAPTCHA and the Google <span>Privacy Policy</span> and <span>Teams of Service</span> apply</p>
        <button class="btn btn-warning">Sign Up</button>
      </div>
    </div>
  </section>
{% endblock content %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static "css/base.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  {% block head %}
  {% endblock head %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Mushroom Cove |</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url "about" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url "explore" %}">Explore</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url "mushroom-index" %}">Catalog</a>
              </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
            <span class="navbar-text">Welcome {{ user }}</span>
            <form class="d-flex" method="post" action="{% url "logout" %}">
              {% csrf_token %}
              <button class="btn btn-outline-success" type="submit">Log out</button>
            </form>
          {% else %}
            <a class="nav-link" href="{% url "login-page" %}">Login</a>
            {% comment %} <a class="nav-link" href="{% url "signup" %}">Sign Up</a> {% endcomment %}
          {% endif %}
        </div>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock content %}
  </main>
  <footer>
    <p class="copy-right">©1997-2024 Mushroom Cove <br>33 East 17th
      Street, New York, NY 10003
    </p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

main_app/templates/explore.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="">
{% endblock head %}
{% block content %}
  <h1>Explore Page</h1>
{% endblock content %}

main_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static "css/home.css" %}">
{% endblock head %}
{% block content %}
  <section class="image-container">
    <img src="{% static "images/mushrooms-fall-foliage.jpg" %}" alt="fall-mushroom">
  </section>
  <section class="intro-container">
    <div>
      <h2>Mushroom are all around us.</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur, aspernatur et excepturi tenetur magnam ea ipsum rerum animi fugit at quis, id sed autem accusantium nulla sunt, odit dolor labore.</p>
    </div>
    <div>
      <h3>Explore More</h3>
      <button class="btn btn-warning">How to Start Foraging</button>
      <button class="btn btn-warning">ID Tips and Skills</button>
      <button class="btn btn-warning">In the Field</button>
    </div>
  </section>
  <section class="info-container">
    <div class="info-content-started">
      <h2>Getting Started</h2>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas sequi, quibusdam iure, hic dolorum illo earum a nemo aperiam aliquam facilis vero possimus qui, deserunt tempora vitae placeat voluptas. Ipsam.</p>
    </div>
    <div class="info-content-find">
      <div>
        <h2>How to Find a Mushroom</h2>
        <p>No matter where you are, guides will help make foraging mushrooms easier</p>
        <button class="btn btn-warning">Read On</button>
      </div>
      <img src="{% static "images/mushroom-basket.jpg" %}" alt="mushroom-basket">
    </div>
  </section>
  <section class="mailing-container">
    <div class="mailing-content blue-gradient">
      <div>
        <h1>JOIN US ON OUR MAILING LIST</h1>
        <p class="mailing-message">Let us send you the latest news and events</p>
      </div>
      <div class="news-letter-signup">
        <label for="email">Email</label>
        <input id="email" type="text">
        <label for="zip">Zip</label>
        <input id="zip" type="text">
        <p>This site is protected by reCAPTCHA and the Google <span>Privacy Policy</span> and <span>Teams of Service</span> apply</p>
        <button class="btn btn-warning">Sign Up</button>
      </div>
    </div>
  </section>
{% endblock content %}

main_app/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static "css/login.css" %}">
{% endblock head %}
{% block content %}
  <section>
    <div class="login-container">
      <img src="{% static "images/mushroom-icon.jpg" %}" alt="mushroom-icon">
      <form action="{% url "home" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}">
        <button class="btn btn-warning" type="submit">Login</button>
      </form>
      <p class="signup-text">If you don't have an account, become a member and sign-up for an account <a href="{% url "signup" %}">here</a>.</p>
    </div>
  </section>
{% endblock content %}

main_app/templates/main_app/mushroom_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block head %}

{% endblock head %}
{% block content %}
  <div>
    <h1>Delete Mushroom</h1>
  </div>
  <h2>Are you sure you want to delete {{ mushroom.name }}</h2>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url "mushroom-detail" mushroom.id %}">Cancel</a>
    <button type="submit">Yes - Delete</button>
  </form>
{% endblock content %}

main_app/templates/main_app/mushroom_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}" />
{% endblock %} 
{% block content %}
<section>
  <div class="form-container">
    <div class="page-header">
      {% if object %}
        <h1>Edit {{ object.name }}</h1>
      {% else %}
        <h1>Add a Mushroom</h1>
      {% endif %}
    </div>
    
    <form action="" method="post">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="btn btn-warning">Submit!</button>
    </form>
  </div>
</section>

{% endblock %}

main_app/templates/mushrooms/detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static "css/mushrooms/mushroom-detail.css" %}">
{% endblock head %}
{% block content %}
  <section class="detail-header">
    <h1>{{ mushroom.name }}</h1>
    <h4>({{ mushroom.scientific }})</h4>
    <div id="carouselExampleIndicators" class="carousel slide">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static "images/mushroom1.jpg" %}" alt="mushroom1">
        </div>
        <div class="carousel-item">
          <img src="{% static "images/mushroom2.jpg" %}" alt="mushroom2">
        </div>
        <div class="carousel-item">
          <img src="{% static "images/mushroom3.jpg" %}" alt="mushroom3">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>
  <section class="detail-content">
    <h2>At a Glance</h2>
    <p class="description">{{ mushroom.description }}</p>
    <div>
      <button class="btn btn-warning">
        <a href="{% url "mushroom-update" mushroom.id %}">Edit</a>
      </button>
      <button class="btn btn-warning">
        <a href="{% url "mushroom-delete" mushroom.id %}">Delete</a>
      </button>
    </div>
  </section>

  <section class="record-form">
    <h3>Record your findings for {{mushroom.name}}</h3>
    <form
      action="{% url "add-tracking" mushroom.id%}"
      method="post"
      autocomplete="off"
    >
      {% csrf_token %}
      {{ tracking_form.as_p}}
      <button class="btn btn-warning" type="submit">Record Mushroom</button>
    </form>
  </section>
  <section class="mushroom-recordings">
    <h3>Records of {{mushroom.name}}</h3>
    {% if mushroom.tracking_set.all.count %}
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Location</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          {% for item in mushroom.tracking_set.all %}
            <tr>
              <td>{{ item.title }}</td>
              <td>{{ item.date }}</td>
              <td>{{ item.location }}</td>
              <td>{{ item.notes }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div>
        <p>There are no records for {{ mushroom.name }}</p>
      </div>
    {% endif %}
  </section>
{% endblock content %}

main_app/templates/mushrooms/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static "css/mushrooms/mushroom-index.css" %}">
{% endblock head %}
{% block content %}
  <section>
    <h1>Your Mushroom Catalog</h1>
    <button class="btn btn-warning btn-add"><a href="{% url "mushroom-create" %}">Add Mushroom</a></button>
    <div class="text-center">
      <div class="row">
        {% for item in mushrooms %}
          <div class="card mushroom-card col-md-3 offset-md-1" style="width: 10rem;">
            <a href="{% url "mushroom-detail" item.id %}">
              <img src="{% static "images/mushroom-icon.jpg" %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">{{item.name}}</h5>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock content %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static "css/signup.css" %}" />
{% endblock %} 
{% block content %}
  <section>
    <div class="signup-container">
      <h1>Create an Account</h1>
      {% if error_message %}
        <p class="red-text">{{ error_message }}</p>
      {% endif %}
      <form action="" method="post" class="form-container" autocomplete="off">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-warning">Submit!</button>
      </form>
    </div>
  </section>
{% endblock %}